#!/usr/bin/env ruby

require 'fileutils'

target_directory = (Time.now - (24 * 60 * 60)).strftime('%Y-%m')
Dir.chdir(File.expand_path('~/Dropbox/Camera Uploads'))

Dir.mkdir(target_directory) rescue Errno::EEXIST
images = Dir.glob('*').select { |path| File.file?(path) } - ["Icon\r"]

FileUtils.move(images, target_directory)
