# https://docs.travis-ci.com/user/languages/ruby
language: ruby
cache: bundler
rvm:
  - 2.4.0

env:
  - PATH=$PATH:$TRAVIS_BUILD_DIR/.scripts

before_install: cd .bitbar

script:
  - bundle exec rspec

# https://docs.travis-ci.com/user/notifications
notifications:
  email: false
