---
task_archive_path: ~/Dropbox/WIP/Tasks
# start_of_the_engagement: 2017-01-01
daily_rate: 300 # 75 * 4

timezones:
  - Europe/Prague
  - Europe/London
  - America/New_York
  - America/Los_Angeles

check_urls:
  - http://blog.botanicus.me
