#!/usr/bin/env zsh


tee /etc/init.d/mosh-server <<EOF
#!/bin/sh
# http://slunked.com/setting-up-mosh-mobile-shell-server-on-debian-squeeze/all/1
# TODO: Rewrite to use systemd.

# export LC_ALL=en_US.UTF-8
# export LANG=en_US.UTF-8
# export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
mosh-server
EOF

chmod +x /etc/init.d/mosh-server
ln -s /etc/init.d/mosh-server /etc/rc3.d/S01mosh-server
ln -s /etc/init.d/mosh-server /etc/rc4.d/S01mosh-server
ln -s /etc/init.d/mosh-server /etc/rc5.d/S01mosh-server
ln -s /etc/init.d/mosh-server /etc/rc2.d/S01mosh-server
# locale-gen?

# TODO: Install nvr.
