#!/bin/sh

if ! test -z "$TMUX"; then
  echo "You're in a TMUX session already."
  echo "Please detach from it first."
  exit 1
else
  cd ~/ars-type
  tmux new -s ars -d
  tmux send-keys -t ars nvim ENTER
  tmux new-window
  tmux new-window "clear; bundle exec rails server"
  cd ~
  tmux attach -t ars
fi
