#!/usr/bin/env ruby

git_aliases = %x{git config --get-regexp alias\.}.scan(/^alias\.([^\s]+)/).flatten
dotfiles_aliases = %x{git --git-dir=#{ENV['HOME']}/dotfiles.git config --get-regexp alias\.}.scan(/^alias\.([^\s]+)/).flatten

custom_executables = ENV['PATH'].split(':').
  select { |dir| dir.match(ENV['HOME']) && ! dir.match(/\bruby\b/) }.
  map { |dir| Dir.glob("#{dir}/*") }.flatten.
  select { |path| File.file?(path) && File.executable?(path) }.
  map { |executable| File.basename(executable) }

git_executables = custom_executables.select { |executable| executable.match(/^git-/) }

puts "Git aliases: #{(git_aliases + git_executables.map { |git_command| git_command[4..-1] }).join(' ')}."
puts "Dotfiles aliases: #{(dotfiles_aliases - git_aliases).join(' ')}"
puts "Scripts: #{(custom_executables - git_executables).join(' ')}."
