#!/bin/zsh

play() {
  while true; do
    echo "~ Playing $1."
    afplay ~/"Dropbox/Media/Meditation/Lifeflow/LifeFlow 2.0 Bonus/$1"
  done
}

case "$1" in
  learn)
    play "02 LifeFlow - Optimal Learning.mp3" ;;
  work)
    play "03 LifeFlow 2.0 - Creative Flow.mp3" ;;
  awaken)
    play "01 LifeFlow - Awaken.mp3" ;;
  nirvana)
    play "04 LifeFlow 2.0 - Nirvana" ;;
  *)
   echo "Usage: $0 [learn|work|awaken|nirvana]" ;;
esac
