#!/bin/sh

# For whatever reason $GIT_DIR is not available in here.
GIT_DIR=$(git rev-parse --git-dir)
HOOK_PATH=$GIT_DIR/hooks/post-commit

echo "$(tput setaf 2)~$(tput sgr0) Installing $(tput setaf 7)$HOOK_PATH$(tput sgr0).\n"

tee $HOOK_PATH <<EOF
#!/bin/sh

BRANCH_NAME=\$(git symbolic-ref --short HEAD)
echo "\$(tput setaf 2)~ \$(tput setaf 7)git push origin \$BRANCH_NAME\$(tput sgr0)\n"
git push -u origin \$BRANCH_NAME
EOF

chmod +x $HOOK_PATH
