#!/bin/sh

# For whatever reason $GIT_DIR is not available in here.
GIT_DIR=$(git rev-parse --git-dir)

HOOK_PATH=$GIT_DIR/hooks/post-commit
echo "~ Installing $HOOK_PATH.\n\n"
tee $HOOK_PATH <<EOF
#!/bin/sh

#git pull -r && git push # This requires stashing, but what if no changes, but there's anything else in stash?
git push
EOF

chmod +x $HOOK_PATH
