#!/usr/bin/env ruby

require 'yaml'
require 'find'
require 'refined-refinements/colours'

PATH = File.expand_path('~/Dropbox/Data/Data/Headspace.yml')

using RR::ColourExts

# headspace play
# headspace start "Health Series/3 - Stress"
# headspace series

def play_next(data)
  if next_episode_files = find_next_episode_files(data)
    next_episode_files.each do |path|
      puts "~ #{path}"
      system("afplay '#{path}'")
    end

    today_episode_number = next_episode_files.first.match(/Day (\d+)/)[1]
    last_episode = data[:episodes].keys.last

    episode_path = "#{File.dirname(last_episode)}/Day #{today_episode_number}"
    data[:episodes][episode_path] = Time.now

    if File.size(PATH) < data.to_yaml.length
      File.open(PATH, 'w') do |file|
        file.puts(data.to_yaml)
      end
    else
      puts "The data we were to write are of a smaller size than the original size. Aborting.\n\n"
      puts data.to_yaml
    end
  else
    abort "No episodes played yet. Which ."
  end
rescue Interrupt
  puts ''
end

def find_next_episode_files(data)
  episodes = data[:episodes] || Hash.new
  if last_episode = episodes.keys.last
    last_episode_day = last_episode.split('/').last.match('Day (\d+)')[1]
    today_episode_number = last_episode_day.to_i + 1

    Dir.glob("#{File.dirname(last_episode)}/*Day*").select do |path|
      # Protection against matching 30 if the day is 3.
      path.match(/Day #{today_episode_number}\b/)
    end
  end
end

def list_series
  directories = Array.new
  Find.find('.') do |path|
    if File.directory?(path) && path.split('/').length == 3
      directories << path[2..-1]
    end
  end

  directories.uniq.group_by { |path| path.split('/').first }.each do |group, dirs|
    puts "<green>#{group}</green>".colourise
    dirs.each do |dir|
      puts "  #{group}/<magenta>#{dir.split('/').last}</magenta>".colourise
    end
    puts
  end
end

def show_next_episode(data)
  if next_episode_path = find_next_episode_files(data).first
    dir, basename = File.split(next_episode_path)
    puts "#{dir}/#{basename.match(/Day \d+/)[0]}"
  else
    exit 1
  end
end

####
data = begin
  YAML.load_file(File.expand_path('~/Dropbox/Data/Data/Headspace.yml'))
rescue Errno::ENOENT
  abort "Write ~/Dropbox/Data/Data/Headspace.yml."
end

Dir.chdir(File.expand_path(data[:base_dir]))

case ARGV.shift
when 'play'   then play_next(data)
when 'next?'  then show_next_episode(data)
when 'series' then list_series
when 'start'  then puts('TODO')
else
  abort DATA.read.colourise
end


__END__
headspace play <bright_black># Start the next episode.</bright_black>
headspace start "Health Series/3 - Stress"
headspace series
