#!/usr/bin/env ruby

# log drink "5 small shots of rum" "5.0"

TYPES = {
  drink: [:drink, :units],
  weight: [:weight],
  expense: [:expense, :price]
}

type = ARGV.first && ARGV.shift.to_sym
unless arg_names = TYPES[type]
  abort "Unknown type #{type}. Types are: #{TYPES.keys.inspect}"
end

unless arg_names.length == ARGV.length
  abort "Invalid length.\nExpected arguments: #{arg_names.inspect}"
end

args = ARGV.length.times.map do
  key, value = arg_names.shift, ARGV.shift
  "'#{key}=#{value}'"
end

puts "now log #{args.join(' ')}"
exec "now log #{args.join(' ')}"
