#!/bin/sh

locale=en_US.UTF-8

export LANG=$locale
export LANGUAGE=$locale
export LC_CTYPE=$locale
export LC_NUMERIC=$locale
export LC_TIME=$locale
export LC_COLLATE=$locale
export LC_MONETARY=$locale
export LC_MESSAGES=$locale
export LC_PAPER=$locale
export LC_NAME=$locale
export LC_ADDRESS=$locale
export LC_TELEPHONE=$locale
export LC_MEASUREMENT=$locale
export LC_IDENTIFICATION=$locale
export LC_ALL=$locale

exec /usr/bin/mosh-server #"$@"
