#!/usr/bin/env ruby

require 'yaml'

type = ARGV.shift

unless ['ruby', 'js'].include?(type)
  abort 'Type has to be ruby or js!'
end

unless name = ARGV.shift
  abort 'Provide a name.'
end

def sh(command)
  puts "$ #{command}"
  puts %x(#{command})
end

def replace_name(content, name, const_name)
  content.gsub!(/%NAME%/, const_name)
  content.gsub!(/%name%/, name)
  content
end

const_name = name.gsub(/[-_](.)/) { |e| $1.upcase }
const_name.sub!(/^(.)/) { |e| $1.upcase }

puts "~ Project #{name}, constant #{const_name}"

data = YAML.load(DATA.read)

sh "mkdir #{name}"

case type
when 'ruby'
  File.open("#{name}/README.md", 'w') do |file|
    file.puts(replace_name(data['readme'], name, const_name))
  end

  File.open("#{name}/.editorconfig", 'w') do |file|
    file.puts(replace_name(data['editorconfig'], name, const_name))
  end

  File.open("#{name}/.rspec", 'w') do |file|
    file.puts(replace_name(data['dotrspec'], name, const_name))
  end

  File.open("#{name}/Gemfile", 'w') do |file|
    file.puts(replace_name(data['gemfile'], name, const_name))
  end

  File.open("#{name}/#{name}.gemspec", 'w') do |file|
    file.puts(replace_name(data['gemspec'], name, const_name))
  end

  sh "chmod +x #{name}/#{name}.gemspec"

  File.open("#{name}/.gitignore", 'w') do |file|
    file.puts(replace_name(data['gitignore'], name, const_name))
  end

  sh "mkdir #{name}/lib"
  sh "mkdir #{name}/lib/#{name}"
  File.open("#{name}/lib/#{name}.rb", 'w') do |file|
    file.puts(replace_name(data['lib_main'], name, const_name))
  end

  sh "mkdir #{name}/spec"
  File.open("#{name}/spec/spec_helper.rb", 'w') do |file|
    file.write('')
  end
when 'js'
  abort 'Not implemented yet.'
end

__END__
gitignore: |
  /*.gem

readme: |
  # About

  # Installation

  ```
  cd %name%
  bundle
  ```

gemfile: |
  source 'https://rubygems.org'

  group(:test) do
    gem 'rspec'
  end

gemspec: |
  #!/usr/bin/env gem build

  Gem::Specification.new do |s|
    s.name              = '%name%'
    s.version           = '0.0.1'
    s.date              = Date.today.to_s
    s.authors           = ['https://github.com/botanicus']
    s.summary           = 'YYY'
    s.description       = 'XXX'
    s.email             = 'james@101ideas.cz'
    s.homepage          = 'https://github.com/botanicus/%name%'
    s.rubyforge_project = s.name
    s.license           = 'MIT'

    s.files             = ['README.md', *Dir.glob('**/*.rb')]

    #s.add_runtime_dependency('http', '~> 0')
  end

editorconfig: |
  # http://EditorConfig.org

  # Don't look into parent directory.
  root = true

  [*]
  charset = utf-8

  # Indentation.
  indent_style = space
  indent_size = 2

  # Whitespace handling.
  end_of_line = lf
  insert_final_newline = true
  trim_trailing_whitespace = true

dotrspec: |
  --color
  --format
  documentation
  #progress

lib_main: |
  module %NAME%
  end
