#!/usr/bin/env ruby

require 'prowl'

def usage
  "#{$0} [notification text] [event] [url]"
end

params = {
  apikey: ENV.fetch('PROWL_API_KEY'),
  application: `hostname`.chomp,
  description: ARGV.shift || abort(usage),
  event: ARGV.shift || ''
}

if url = ARGV.shift
  params.merge!(url: url)
end

p params

Prowl.add(params)
