#!/bin/bash

help() {
  echo "=== Help ==="
  echo "publish add CV.pdf"
  echo "publish rm CV.pdf"
  echo "publish list"
  echo "publish run 'command'"
}
command=$1 && shift
case $command in
add)
  for file in $* ; do
    scp -r "$file" tagadab:/webs/static/static.101ideas.cz/site > /dev/null
    echo "http://static.101ideas.cz/$(basename $file)"
  done ;;
ls|list)
  ssh tagadab ls -l /webs/static/static.101ideas.cz/site ;;
rm|del|delete)
  for file in $* ; do
    ssh tagadab rm -rf /webs/static/static.101ideas.cz/site/$file
  done ;;
run)
  ssh tagadab "cd /webs/static/static.101ideas.cz/site && $*" ;;
*)
  help ;;
esac
