#!/usr/bin/env ruby

# === About ===
# Current rates for most important currencies.
# Used daily actualized data from CNB.

# TODO: bitcoin

require "open-uri"
require "term/ansicolor"

String.send(:include, Term::ANSIColor)

# array of countries you are interested in
# country name in CNB file => print representation
followed = {"US" => "USD", "EMU" => "EUR", "UK" => "GBP"}
text = "http://www.cnb.cz/cs/financni_trhy/devizovy_trh/kurzy_devizoveho_trhu/denni_kurz.txt"

open(text) do |stream|
  date = stream.readline.chomp.bold
  puts "Data from #{date}"
  stream.readlines.each do |line|
    # země|měna|množství|kód|kurz
    data = line.chomp.split("|")
    rate = data.last.sub(",", ".").to_f / data[2].to_i
    if followed.keys.include?(data[0])
      rounded = "#{rate.round} CZK".bold.green
      rate = "#{rate} CZK".bold.blue
      country = followed[data[0]].bold.red
      puts "#{country}: #{rate} (rounded to #{rounded})"
    end
  end
end
