#!/bin/sh

if ! test -z "$TMUX"; then
  echo "You're in a TMUX session already."
  echo "Please detach from it first."
  exit 1
else
  cd ~/riffr
  tmux new -s riffr -d
  tmux send-keys -t riffr nvim ENTER
  tmux new-window
  tmux new-window "clear; bundle exec rails server --binding 'ssl://0.0.0.0:3000?key=config/certs/localhost.key&cert=config/certs/localhost.crt'"
  cd ~
  tmux attach -t riffr
fi
