#!/bin/sh

# Inspired by https://gist.github.com/todgru/6224848
cd ~/Desktop

tmux new -d -s sys

# Window 1: IRB & ZSH.
tmux send-keys 'pry' C-m C-l
tmux splitw -h -p 55
tmux rename-window 'IRB::ZSH'

# Window 2: Tasks.
tmux new-window -n tasks
tmux send-keys C-l 'now e' C-m
tmux splitw -h
tmux send-keys C-l 'now e t' C-m

# Window 3: Scheduler.
tmux new-window -n scheduler
tmux send-keys 'cd ~/Dropbox/Data' C-m
tmux send-keys C-l './Services/scheduler.rb' C-m
tmux splitw -h -p 55
tmux send-keys C-l 'nvim Services/scheduler.rb' C-m

tmux select-window -t sys:2
tmux attach-session -t sys

echo -ne "\e]1;sys\a"
