#!/bin/sh

#echo "~ OS X updates."
#sudo softwareupdate -i -a

echo "~ Homebrew updates."
brew update && brew upgrade && brew cleanup

if which npm; then
  echo "~ NPM updates."
  npm install npm -g
  npm update -g
fi

echo "~ APM & Vim updates."
apm upgrade --no-confirm
vim -c VundleUpdate -c quitall

echo "~ Ruby updates."
ruby-install # Prints current versions.
ruby-install ruby --latest --no-reinstall

echo "~ RubyGems updates."
gem update --system && gem update && gem cleanup
