#!/bin/sh

#echo "~ OS X updates."
#sudo softwareupdate -i -a

echo "~ Homebrew updates."
brew update && brew upgrade && brew cleanup

echo "~ Homebrew Cask updates."
brew cask upgrade && brew cask cleanup

if which npm; then
  echo "~ NPM updates."
  npm install npm -g
  npm update -g
fi

echo "~ Vim updates."
vim -c PlugUpdate -c PlugUpgrade -c quitall

# Skipped, it removes older gems that a project locked in through Gemfile.lock.
#echo "~ RubyGems updates."
#gem update --system && gem update && gem cleanup
